{% set version = "3.2.4" %}

package:
  name: nfft
  version: {{ version }}

source:
  fn: nfft-{{ version }}.tar.gz
  url: https://www-user.tu-chemnitz.de/~potts/nfft/download/nfft-{{ version }}.tar.gz
  sha256: 31932438bd28609bcc32bef23830994fe6ac26d411d2077cde782faa5d21207e

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
  host:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw
    - cunit
    - ncurses
  run:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw

test:
  commands:
    - test -f ${PREFIX}/lib/libnfft3.a
    - test -f ${PREFIX}/lib/libnfft3.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3_threads.a
    - test -f ${PREFIX}/lib/libnfft3_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3_threads.dylib  # [osx]

about:
  home: http://www.nfft.org/
  license: GPLv2
  summary: Non-equispaced fast Fourier transform (NFFT) library

extra:
  recipe-maintainers:
    - ghisvail
    - grlee77
    - kohr-h
