{% set version = "3.5.0" %}

package:
  name: nfft
  version: {{ version }}

source:
  fn: nfft-{{ version }}.tar.gz
  url: https://github.com/NFFT/nfft/releases/download/{{ version }}/nfft-{{ version }}.tar.gz
  sha256: 5f78a9d2a675aee7ace55c96bdf1b54f049e05a1dd50697757bdc609a8586a07

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
  host:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw
    - cunit
    - ncurses
  run:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw

test:
  commands:
    - test -f ${PREFIX}/lib/libnfft3.a
    - test -f ${PREFIX}/lib/libnfft3.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3_threads.a
    - test -f ${PREFIX}/lib/libnfft3_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3_threads.dylib  # [osx]

about:
  home: http://www.nfft.org/
  license: GPLv2
  summary: Non-equispaced fast Fourier transform (NFFT) library

extra:
  recipe-maintainers:
    - ghisvail
    - grlee77
    - kohr-h
