# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XMjF7Jti/hFhrGSo7oRu3eit63g9aOQK3aoEy6HVh9j22mEZltZbqUseAgT+RVu0QbfngKM1w93SpG1BxjZUsWF7itbqkx5dQ3MceWvmVDoyFN2lc+DzFut3UcKCCTVTcte3vOkoBzAu23LQLhGP3IBHTrT6aFLrMAbZIbFXMkUBqzwqZqHS9C6yJYB+RpAPIbl6NokiXt42tOxfZwVMVbvN47pA2bge9CUwqhS046NLM6i7Wk0ufb8Kd23AYz+0kJUZ6yQsZWBCDV2CAq43R22UO1SEnoHNH6ohFl1Tao1JdYpP1jhdUVu8nvdoNYt0P5AiqBahgUUpAntbEJ9a21L7AOg13bDqiH9XXvoaA1H1mDuxQDKutkGgEKzMOBfal1YYnCc/TqA5bwTRBy0fLC/uJPPDC3iIsQDjn0PrrH+1ojGz5bZBuUiLRDYA++Ph8CzUQHyI2fANw2xSChf8HJi8HAIOuCSA7SQCZU9fKej5ixns70hkpMkhrYNU2E4PkBJIqWC+JFgW7SL8c5dwweUQ4/oQS2HYev0FfA7k9TqNz1QdBO9nIZuBs+baY8yIbnhhW3HUkSsDY8K+qqNGAkeRF0OcA+0gReheF8cpsZnImwH+T+dvDAtjZD+CwjuvOgCUcaZXy+Aft/wiBoboPbtcFjuPwetBCa5XHNEWFdY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
