travis:
  secure:
    BINSTAR_TOKEN: ZTtd2JZUQtP1gLwtGTWQlBmQ791PV5wEecrxZ11Vet3sfijXxJaoLDGtKLglsljN0znoWWct6lfvCSqn+LDFfYTax1I2XTyyvd4Ig9n6OKdRQsNHZ6Nh4dKxUjgrWaU4f0JXTa3Yeh9xikbWihEsRLyWL/fxZH+14OJKQCqE52iYrld4vCm17Nyw6/PpU1/ShikVz42wkNPMJNcUDkK9sFfn3Gs4ohqaUSuYAtzIeqsG7gCPjrpgwrnaD7FFF+E6injI6v9T5ErCfl+2mT3FaWOTFESnF1fyBDhFy1JdDhAUW8j+feVV9vOGGjvQ0wLRZqp3PrcukGzfmZ+VIHpRiX2KtP9kjvr+yInXsGeATVc27nJiUMQJoQZacFPSPO/vwtS4tzH7RfGpgSwD4YUTvlqYIGsN8C5bY6u/MK2cifSQs+95rq3cifZDCaK5gCR4npoKzBuiW+Y1jT9P4SFPfNOF7tDyv2MCH65wcfQr8V6dA6pgNyzWw8+tgSzck89jwgGVQdjgxrtFgCpqAcHazmXWYg4BEZYec+eY5SKKpUE+N3bKwnVjhkKLkGl2PbxLcpPOtmhSOJN9yJ8uyMOwyAsSo5xX1SFsYiFp7PzvzPehPcN4d7UtaiToAjcsV92PwWYL/BcYzww7P06B2Kroaxi82zuRQvuzI5tYPdTC/vg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
