appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IesDt8dNCKgqujGRTOa9WFvHzbP/wLNFMnBKmeMlUz9JeOHwIWn++ouIlKNMAaYoR6Q6u1ujj3e0+s2IKHZqSan4VMOfJYP3ZJCm1KQ/mu87COlNd8Q9oF1DAxkLOyJfIEKxxEodTYRjM8Hrp1bigwl4L3lGGJSpcAw6TssKXz8cTldWwzEZJmcmlEcyqQpxV7iUmG6WMumJRIaEn35JhZOoW0i7spfdGLsrFKc4Ab8GgeTMup8skhNfs9fxCqpMsQe/L1kykTwB89If+rJt8W71U3qGmQED4yB394WLj3Jz6nFaZWk/rXT1xAntXZxdP6mdbxhuEG3+0lnuARoZcQGTOx3Te8pUeGjPnPOVb2KcJ7L25g3B6foOOta87akr0e7e9MXVC0oxl/qmoZe3TT400WVSxIq6soYS1c3MdX/2iJdtNtmgXIRTTkVK9OKdhfwKG2TSlfmC/fN5GxH+NOlQ6xscJz2DzyIMO99pD0iJ4wteUbtzbZqHepFG+eT3rK+fC1tKSZEG/GUZZsIbpfkiZboDtlrSih1/CVGAR4HB7MaNN8D1B6pLyoH0j1WBdiFPsKsk8beasLHZ0ydFBzBSI1MJqQ/fCC3CO/chxbFYh9xFOHPo2oqPhMIvZcCZVo2emfBXxzzOkfDGnkAtlz8qMLkwBg0F0WFov3JfKmc=}
