travis:
  secure:
    BINSTAR_TOKEN: XMjF7Jti/hFhrGSo7oRu3eit63g9aOQK3aoEy6HVh9j22mEZltZbqUseAgT+RVu0QbfngKM1w93SpG1BxjZUsWF7itbqkx5dQ3MceWvmVDoyFN2lc+DzFut3UcKCCTVTcte3vOkoBzAu23LQLhGP3IBHTrT6aFLrMAbZIbFXMkUBqzwqZqHS9C6yJYB+RpAPIbl6NokiXt42tOxfZwVMVbvN47pA2bge9CUwqhS046NLM6i7Wk0ufb8Kd23AYz+0kJUZ6yQsZWBCDV2CAq43R22UO1SEnoHNH6ohFl1Tao1JdYpP1jhdUVu8nvdoNYt0P5AiqBahgUUpAntbEJ9a21L7AOg13bDqiH9XXvoaA1H1mDuxQDKutkGgEKzMOBfal1YYnCc/TqA5bwTRBy0fLC/uJPPDC3iIsQDjn0PrrH+1ojGz5bZBuUiLRDYA++Ph8CzUQHyI2fANw2xSChf8HJi8HAIOuCSA7SQCZU9fKej5ixns70hkpMkhrYNU2E4PkBJIqWC+JFgW7SL8c5dwweUQ4/oQS2HYev0FfA7k9TqNz1QdBO9nIZuBs+baY8yIbnhhW3HUkSsDY8K+qqNGAkeRF0OcA+0gReheF8cpsZnImwH+T+dvDAtjZD+CwjuvOgCUcaZXy+Aft/wiBoboPbtcFjuPwetBCa5XHNEWFdY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
