travis:
  secure:
    BINSTAR_TOKEN: G4onVduhVRO0zXHJREdSpyyFiLkAPMlhZ5xeWNBqFX1sRA1NJYGQrn5SYZ5XT3jBuh8AdcLwRS6QK0PwQQBeGeHxH75ATlIFu0Kj+XwnsWHf3ZPipJKcjrVcud39v9MECmHqlSigBweWVM+BsotuGQjO7sDTx3u+jVCaTgcGLxvHXFrPUwARUZhsn01ZcRlVCCr09Zb00lWlrOzUs5B27qLBnD/qIeGOCEf+WAMi7bDlPFNKgxlQARqP2JONTzUH+nz7mIz+yPAxUbox/dZYVuOwa49WPMvAFmMaJkOjoqJ0EAKk6JJZSaJSYNMGT1jh7LAbQK0ujJ25BMWx8biSQqOfPlU8HF1LfzpKCS+os66SiPsysyUPkTDK+MreGJ0w1UcqKqRpo8OZhCuzY2mlEASKqpVMoNYNcKhl7S0AJnQXxy7Em/FIA9BwH3Fuj3xAkV+W9boFbtsFMfNPwbYnNIdtBoftgkpV1bTG0X0B08lUnw27VPdA/5pcmrND+rgdS9iKr3P0pYTl77cGY3ufB+AUSGX7+BXIdcpZ8xRv5eElXDfwf04eO0FK0+9liCM0x72u3GfJ3dVumiFuBs5EpZMwzRnp69rs4xxb9yyq3YEJNvpR/bDwfHknQLT9VQuk0NQSxZeFMtK5qFZfki5n5IvDf++a1p2uHHwQyroiVVc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
